baseURL = 'https://anushacs-dell.github.io/website1'
languageCode = 'en-us'
theme = 'zoo-project'

[params]
description = 'The ZOO-Project is an open source processing platform, released under MIT/X11 Licence. It provides the polyglot ZOO-Kernel, a server implementation of the Web Processing Service (WPS) (1.0.0 and 2.0.0) and the OGC API - Processes standards published by the OGC'

# navigation
  [menu]
     [[menu.main]]
     identifier = "index"
      name = "Index"
      url = "/"
      weight = 1

    [[menu.main]]
      identifier = "services"
       name = "Services"
       url = "/code/services/"
       parent = "code"
       weight = 2

    [[menu.main]]
      identifier = "about"
      name = "About"
      url = "#"
      weight = 2
      hasChildren = true

    [[menu.main]]
      identifier = "introduction"
      name = "Introduction"
      url = "https://zoo-project.github.io/docs/intro.html"
      parent = "about"
      weight = 3

     [[menu.main]]
      identifier = "tribe"
      name = "Tribe"
      url = "/about/tribe/"
      parent = "about"
      weight = 4

      [[menu.main]]
      identifier = "event"
      name = "Event"
      url = "/about/event/"
      parent = "about"
      weight = 5

      [[menu.main]]
      identifier = "identity"
      name = "Identity"
      url = "/about/identity/"
      parent = "about"
      weight = 6

      [[menu.main]]
      identifier = "resources"
      name = "Resources"
      url = "#"
      weight = 2
      hasChildren = true

      [[menu.main]]
      identifier = "download"
      name = "Download"
      url = "/resources/download/"
      parent = "resources"
      weight = 3

      [[menu.main]]
      identifier = "userguide"
      name = "Userguide"
      url = "/resources/userguide/"
      parent = "resources"
      weight = 4

      [[menu.main]]
      identifier = "workshops"
      name = "Workshops"
      url = "/resources/workshops/"
      parent = "resources"
      weight = 5

      [[menu.main]]
      identifier = "API"
      name = "API"
      url = "https://zoo-project.github.io/docs/C_API/"
      parent = "resources"
      weight = 6

      [[menu.main]]
      identifier = "examples"
      name = "Examples"
      url = "/resources/examples/"
      parent = "resources"
      weight = 7

      [[menu.main]]
      identifier = "spatialtools"
      name = "Spatial Tools"
      url = "/resources/examples/spatialtools/"
      parent = "examples"
      weight = 8

      [[menu.main]]
      identifier = "presentation"
      name = "Presentation"
      url = "/resources/presentation/"
      parent = "resources"
      weight = 9



    

      [[menu.main]]
      identifier = "get-involved"
      name = "Get Involved"
      url = "#"
      weight = 2
      hasChildren = true

      [[menu.main]]
      identifier = "sponsorship"
      name = "Sponsorship"
      url = "/resources/sponsorship/"
      parent = "get-involved"
      weight = 3

      [[menu.main]]
      identifier = "trac"
      name = "Trac/SVN"
      url = "/resources/trac/"
      parent = "get-involved"
      weight = 4

      [[menu.main]]
      identifier = "knowledge_partners"
      name = "knowledge Partners"
      url = "/resources/knowledge_partners/"
      parent = "get-involved"
      weight = 5

      [[menu.main]]
      identifier = "feed_animals"
      name = "Feed Animals"
      url = "/resources/feed_animals/"
      parent = "get-involved"
      weight = 6


